const Scheme = require('../models/Scheme.model');

const MASTER_SCHEMES = [
  {
    name: 'INSPIRE Scholarship for Higher Education (SHE)',
    provider: 'Department of Science and Technology (DST), Govt of India',
    ministry: 'Department of Science and Technology',
    description: 'Financial assistance for meritorious students pursuing Natural and Basic Sciences courses (B.Sc., B.S., Int. M.Sc.) at top institutions in India.',
    amount: '₹80,000 / year',
    amountValue: 80000,
    category: 'General',
    status: 'Open',
    officialApplicationUrl: 'https://online-inspire.gov.in',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Income Certificate', '12th Marksheet', 'College Admission Proof'],
    eligibilityCriteria: {
      minScore: 85,
      incomeLimit: 800000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 17,
      maxAge: 22,
      educationLevels: ['12th Pass', 'Graduation'],
      streams: ['Science']
    }
  },
  {
    name: 'PM Scholarship Scheme (PMSS) for CAPF & AR',
    provider: 'Welfare and Rehabilitation Board (WARB), Ministry of Home Affairs',
    ministry: 'Ministry of Home Affairs',
    description: 'Financial support for dependent wards and widows of Central Armed Police Forces & Assam Rifles personnel for professional degree courses.',
    amount: '₹36,000 / year',
    amountValue: 36000,
    category: 'General',
    status: 'Open',
    officialApplicationUrl: 'https://scholarships.gov.in',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Service Certificate', '12th Marksheet', 'Domicile Certificate'],
    eligibilityCriteria: {
      minScore: 60,
      incomeLimit: 600000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 17,
      maxAge: 25,
      educationLevels: ['12th Pass', 'Graduation', 'Post Graduation'],
      streams: ['Engineering', 'Medical', 'Science', 'Commerce', 'Arts', 'Diploma']
    }
  },
  {
    name: 'Central Sector Scheme of Scholarships for College and University Students (CSSS)',
    provider: 'Department of Higher Education, Ministry of Education',
    ministry: 'Ministry of Education',
    description: 'Scholarships for meritorious college and university students from low-income families to meet their day-to-day educational expenses.',
    amount: '₹20,000 / year',
    amountValue: 20000,
    category: 'General',
    status: 'Open',
    officialApplicationUrl: 'https://scholarships.gov.in',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Income Certificate', '12th Marksheet', 'Bank Passbook'],
    eligibilityCriteria: {
      minScore: 80,
      incomeLimit: 450000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 17,
      maxAge: 25,
      educationLevels: ['12th Pass', 'Graduation', 'Post Graduation'],
      streams: ['Science', 'Commerce', 'Arts', 'Engineering']
    }
  },
  {
    name: 'Pragati Scholarship Scheme for Girl Students (Technical Degree)',
    provider: 'All India Council for Technical Education (AICTE)',
    ministry: 'Ministry of Education',
    description: 'Empowering young women pursuing AICTE-approved technical degree programs across India.',
    amount: '₹50,000 / year',
    amountValue: 50000,
    category: 'Minority',
    status: 'Open',
    officialApplicationUrl: 'https://www.aicte-india.org/schemes/students-development-schemes/PRAGATI-SCHEME',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Income Certificate', '12th Marksheet', 'College Identity Card'],
    eligibilityCriteria: {
      minScore: 60,
      incomeLimit: 800000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'Female',
      minAge: 16,
      maxAge: 25,
      educationLevels: ['12th Pass', 'Graduation', 'Diploma'],
      streams: ['Engineering', 'Diploma', 'Science']
    }
  },
  {
    name: 'Saksham Scholarship Scheme for Specially-Abled Students (Technical Degree)',
    provider: 'All India Council for Technical Education (AICTE)',
    ministry: 'Ministry of Education',
    description: 'Financial aid for specially-abled students with disability not less than 40% pursuing technical degree courses.',
    amount: '₹50,000 / year',
    amountValue: 50000,
    category: 'General',
    status: 'Open',
    officialApplicationUrl: 'https://scholarships.gov.in',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Disability Certificate (40%+)', 'Income Certificate', '12th Marksheet'],
    eligibilityCriteria: {
      minScore: 50,
      incomeLimit: 800000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 16,
      maxAge: 30,
      educationLevels: ['12th Pass', 'Graduation', 'Diploma'],
      streams: ['Engineering', 'Diploma', 'Science', 'Other']
    }
  },
  {
    name: 'Swanath Scholarship Scheme for Orphans and Affected Children',
    provider: 'All India Council for Technical Education (AICTE)',
    ministry: 'Ministry of Education',
    description: 'Financial support for orphans, children whose both parents died due to Covid-19, or children of armed forces/paramilitary martyred in action.',
    amount: '₹50,000 / year',
    amountValue: 50000,
    category: 'General',
    status: 'Open',
    officialApplicationUrl: 'https://www.aicte-india.org',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Orphan / Death Certificate', 'Income Certificate', '12th Marksheet'],
    eligibilityCriteria: {
      minScore: 50,
      incomeLimit: 800000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 16,
      maxAge: 25,
      educationLevels: ['12th Pass', 'Graduation', 'Diploma'],
      streams: ['Engineering', 'Diploma', 'Science', 'Arts']
    }
  },
  {
    name: 'PG Indira Gandhi Scholarship for Single Girl Child',
    provider: 'University Grants Commission (UGC)',
    ministry: 'Ministry of Education',
    description: 'Support for single girl children pursuing non-professional Master degree programs in recognized universities.',
    amount: '₹36,200 / year',
    amountValue: 36200,
    category: 'Minority',
    status: 'Open',
    officialApplicationUrl: 'https://scholarships.gov.in',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Single Girl Affidavit', 'Graduation Marksheet', 'College Admission Proof'],
    eligibilityCriteria: {
      minScore: 55,
      incomeLimit: 1000000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'Female',
      minAge: 20,
      maxAge: 30,
      educationLevels: ['Post Graduation'],
      streams: ['Science', 'Commerce', 'Arts']
    }
  },
  {
    name: 'PG Scholarship for University Rank Holders',
    provider: 'University Grants Commission (UGC)',
    ministry: 'Ministry of Education',
    description: 'Scholarship awarded to 1st and 2nd rank holders in university undergraduate examinations pursuing Post-Graduation.',
    amount: '₹31,000 / year',
    amountValue: 31000,
    category: 'General',
    status: 'Open',
    officialApplicationUrl: 'https://scholarships.gov.in',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Rank Certificate', 'UG Marksheet', 'College Admission Letter'],
    eligibilityCriteria: {
      minScore: 75,
      incomeLimit: 1000000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 20,
      maxAge: 30,
      educationLevels: ['Post Graduation'],
      streams: ['Science', 'Commerce', 'Arts']
    }
  },
  {
    name: 'Ishan Uday Special Scholarship Scheme for North Eastern Region',
    provider: 'UGC & Ministry of Development of North Eastern Region (MDoNER)',
    ministry: 'Ministry of Development of North Eastern Region',
    description: 'Special scholarship scheme to enhance higher education access for students residing in the North Eastern Region of India.',
    amount: '₹93,600 / year',
    amountValue: 93600,
    category: 'General',
    status: 'Open',
    officialApplicationUrl: 'https://scholarships.gov.in',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Domicile Certificate (NE Region)', '12th Marksheet', 'Income Certificate'],
    eligibilityCriteria: {
      minScore: 60,
      incomeLimit: 450000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['Assam', 'Arunachal Pradesh', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Sikkim', 'Tripura'],
      gender: 'All',
      minAge: 17,
      maxAge: 25,
      educationLevels: ['12th Pass', 'Graduation'],
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Medical']
    }
  },
  {
    name: 'Post Matric Scholarship for SC Students',
    provider: 'Ministry of Social Justice and Empowerment',
    ministry: 'Ministry of Social Justice and Empowerment',
    description: 'Comprehensive financial assistance covering full tuition fees and maintenance allowances for SC students studying at post-matric level.',
    amount: '₹18,000 / year',
    amountValue: 18000,
    category: 'SC',
    status: 'Open',
    officialApplicationUrl: 'https://scholarships.gov.in',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Caste Certificate (SC)', 'Income Certificate', 'Marksheet'],
    eligibilityCriteria: {
      minScore: 50,
      incomeLimit: 250000,
      categories: ['SC'],
      states: ['All'],
      gender: 'All',
      minAge: 15,
      maxAge: 35,
      educationLevels: ['10th Pass', '12th Pass', 'Diploma', 'Graduation', 'Post Graduation'],
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Medical', 'Diploma', 'ITI']
    }
  },
  {
    name: 'Post Matric Scholarship for ST Students',
    provider: 'Ministry of Tribal Affairs, Govt of India',
    ministry: 'Ministry of Tribal Affairs',
    description: 'Financial aid providing maintenance allowance and fee coverage for ST candidates in post-secondary and higher education.',
    amount: '₹18,000 / year',
    amountValue: 18000,
    category: 'ST',
    status: 'Open',
    officialApplicationUrl: 'https://tribal.nic.in',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'ST Tribe Certificate', 'Income Certificate', 'Marksheet'],
    eligibilityCriteria: {
      minScore: 50,
      incomeLimit: 250000,
      categories: ['ST'],
      states: ['All'],
      gender: 'All',
      minAge: 15,
      maxAge: 35,
      educationLevels: ['10th Pass', '12th Pass', 'Diploma', 'Graduation', 'Post Graduation'],
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Medical', 'Diploma', 'ITI']
    }
  },
  {
    name: 'Post Matric Scholarship for OBC Students',
    provider: 'Department of Social Justice & Empowerment',
    ministry: 'Ministry of Social Justice and Empowerment',
    description: 'Educational financial support for Other Backward Classes (OBC) students pursuing post-matriculation or post-secondary courses.',
    amount: '₹15,000 / year',
    amountValue: 15000,
    category: 'OBC',
    status: 'Open',
    officialApplicationUrl: 'https://scholarships.gov.in',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'OBC Certificate', 'Income Certificate', '10th/12th Marksheet'],
    eligibilityCriteria: {
      minScore: 50,
      incomeLimit: 250000,
      categories: ['OBC'],
      states: ['All'],
      gender: 'All',
      minAge: 15,
      maxAge: 30,
      educationLevels: ['10th Pass', '12th Pass', 'Diploma', 'Graduation', 'Post Graduation'],
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Diploma', 'ITI']
    }
  },
  {
    name: 'Pre-Matric Scholarship for Minorities',
    provider: 'Ministry of Minority Affairs, Govt of India',
    ministry: 'Ministry of Minority Affairs',
    description: 'Financial grant for minority students (Muslim, Christian, Sikh, Buddhist, Jain, Parsi) in classes 1 to 10 to reduce dropout rates.',
    amount: '₹10,000 / year',
    amountValue: 10000,
    category: 'Minority',
    status: 'Open',
    officialApplicationUrl: 'https://scholarships.gov.in',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Self Declaration of Minority Status', 'Income Certificate', 'School Marksheet'],
    eligibilityCriteria: {
      minScore: 50,
      incomeLimit: 100000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 6,
      maxAge: 16,
      educationLevels: ['Below 10th', '10th Pass'],
      streams: ['Science', 'Arts', 'Not Applicable']
    }
  },
  {
    name: 'Post-Matric Scholarship for Minorities',
    provider: 'Ministry of Minority Affairs, Govt of India',
    ministry: 'Ministry of Minority Affairs',
    description: 'Post-secondary education grant for minority students pursuing Higher Secondary, Diploma, Graduation, and Post-Graduation.',
    amount: '₹15,000 / year',
    amountValue: 15000,
    category: 'Minority',
    status: 'Open',
    officialApplicationUrl: 'https://scholarships.gov.in',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Minority Community Certificate', 'Income Certificate', '10th/12th Marksheet'],
    eligibilityCriteria: {
      minScore: 50,
      incomeLimit: 200000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 16,
      maxAge: 30,
      educationLevels: ['11th', '12th Pass', 'Diploma', 'Graduation', 'Post Graduation'],
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Medical', 'Diploma']
    }
  },
  {
    name: 'Merit-cum-Means Scholarship for Professional and Technical Courses CS',
    provider: 'Ministry of Minority Affairs',
    ministry: 'Ministry of Minority Affairs',
    description: 'Financial assistance for meritorious minority candidates pursuing professional and technical undergraduate/postgraduate courses.',
    amount: '₹30,000 / year',
    amountValue: 30000,
    category: 'Minority',
    status: 'Open',
    officialApplicationUrl: 'https://scholarships.gov.in',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Minority Affidavit', 'Income Certificate', '12th/UG Marksheet'],
    eligibilityCriteria: {
      minScore: 50,
      incomeLimit: 250000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 17,
      maxAge: 30,
      educationLevels: ['12th Pass', 'Graduation', 'Post Graduation'],
      streams: ['Engineering', 'Medical', 'Science', 'Diploma']
    }
  },
  {
    name: 'Begum Hazrat Mahal National Scholarship',
    provider: 'Maulana Azad Education Foundation (MAEF)',
    ministry: 'Ministry of Minority Affairs',
    description: 'Scholarship specifically for girl students belonging to national minority communities studying in Classes 9th to 12th.',
    amount: '₹12,000 / year',
    amountValue: 12000,
    category: 'Minority',
    status: 'Open',
    officialApplicationUrl: 'https://maef.nic.in',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'School Verification Form', 'Minority Certificate', 'Income Certificate'],
    eligibilityCriteria: {
      minScore: 50,
      incomeLimit: 200000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'Female',
      minAge: 14,
      maxAge: 19,
      educationLevels: ['Below 10th', '10th Pass', '12th Pass'],
      streams: ['Science', 'Commerce', 'Arts', 'Not Applicable']
    }
  },
  {
    name: 'Kotak Kanya Scholarship',
    provider: 'Kotak Education Foundation & Kotak Mahindra Group',
    ministry: 'Corporate Social Responsibility (CSR)',
    description: 'Financial assistance for meritorious girl students from low-income families pursuing professional degree programs in premier institutions.',
    amount: '₹150,000 / year',
    amountValue: 150000,
    category: 'Minority',
    status: 'Open',
    officialApplicationUrl: 'https://kotak-education.org/kotak-kanya-scholarship',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Income Certificate (< ₹6 Lakh)', '12th Marksheet (85%+)', 'NIRF College Fee Receipt'],
    eligibilityCriteria: {
      minScore: 85,
      incomeLimit: 600000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'Female',
      minAge: 17,
      maxAge: 23,
      educationLevels: ['12th Pass', 'Graduation'],
      streams: ['Engineering', 'Medical', 'Science', 'Other']
    }
  },
  {
    name: 'HDFC Bank Parivartan ECSS Scholarship',
    provider: 'HDFC Bank Parivartan CSR Initiative',
    ministry: 'Corporate Social Responsibility (CSR)',
    description: 'Scholarship supporting students from Class 1 to Postgraduate level who face personal or family crises.',
    amount: '₹75,000 / year',
    amountValue: 75000,
    category: 'General',
    status: 'Open',
    officialApplicationUrl: 'https://www.hdfcbank.com/csr/parivartan-ecss',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Income Certificate', 'Previous Year Marksheet', 'Crisis Proof Document'],
    eligibilityCriteria: {
      minScore: 55,
      incomeLimit: 600000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 15,
      maxAge: 28,
      educationLevels: ['10th Pass', '12th Pass', 'Diploma', 'Graduation', 'Post Graduation'],
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Medical', 'Diploma']
    }
  },
  {
    name: 'Reliance Foundation Undergraduate Scholarship',
    provider: 'Reliance Foundation',
    ministry: 'Corporate Social Responsibility (CSR)',
    description: 'Scholarship program supporting first-year undergraduate students in any stream to pursue degree studies.',
    amount: '₹50,000 / year',
    amountValue: 50000,
    category: 'General',
    status: 'Open',
    officialApplicationUrl: 'https://scholarships.reliancefoundation.org',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Income Certificate', '12th Marksheet', 'College Enrolment Letter'],
    eligibilityCriteria: {
      minScore: 60,
      incomeLimit: 1500000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 17,
      maxAge: 24,
      educationLevels: ['12th Pass', 'Graduation'],
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Medical', 'Other']
    }
  },
  {
    name: 'Aditya Birla Capital Scholarship Program',
    provider: 'Aditya Birla Capital Foundation',
    ministry: 'Corporate Social Responsibility (CSR)',
    description: 'Financial aid program for students from Class 9 to Graduation pursuing general and professional degrees.',
    amount: '₹60,000 / year',
    amountValue: 60000,
    category: 'General',
    status: 'Open',
    officialApplicationUrl: 'https://adityabirlacapital.com/csr-scholarship',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Income Certificate (< ₹6L)', 'Marksheet', 'Bank Account Proof'],
    eligibilityCriteria: {
      minScore: 60,
      incomeLimit: 600000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 14,
      maxAge: 25,
      educationLevels: ['Below 10th', '10th Pass', '12th Pass', 'Diploma', 'Graduation'],
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Diploma']
    }
  },
  {
    name: 'Keep India Smiling Foundational Scholarship',
    provider: 'Colgate-Palmolive India Ltd & Buddy4Study',
    ministry: 'Corporate Social Responsibility (CSR)',
    description: 'Foundational support for students in 11th, Graduation, Engineering, BD/Dental, or Sports Training.',
    amount: '₹75,000 / year',
    amountValue: 75000,
    category: 'General',
    status: 'Open',
    officialApplicationUrl: 'https://www.colgate.co.in/keep-india-smiling-scholarship',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Income Certificate', '10th/12th Marksheet', 'Fee Receipt'],
    eligibilityCriteria: {
      minScore: 60,
      incomeLimit: 500000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 15,
      maxAge: 25,
      educationLevels: ['10th Pass', '12th Pass', 'Graduation', 'Diploma'],
      streams: ['Science', 'Medical', 'Engineering', 'Commerce', 'Arts']
    }
  },
  {
    name: 'Tata Capital Pankh Scholarship Program',
    provider: 'Tata Capital CSR Initiative',
    ministry: 'Corporate Social Responsibility (CSR)',
    description: 'Scholarship scheme empowering deserving students in 11th, 12th, General Graduation, and Professional courses.',
    amount: '₹50,000 / year',
    amountValue: 50000,
    category: 'General',
    status: 'Open',
    officialApplicationUrl: 'https://www.tatacapital.com/csr/pankh-scholarship.html',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Income Certificate', 'Previous Class Marksheet', 'School/College ID'],
    eligibilityCriteria: {
      minScore: 60,
      incomeLimit: 400000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 15,
      maxAge: 25,
      educationLevels: ['10th Pass', '12th Pass', 'Diploma', 'Graduation'],
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Diploma']
    }
  },
  {
    name: 'LIC HFL Vidyadhan Scholarship',
    provider: 'LIC Housing Finance Limited (LIC HFL)',
    ministry: 'Corporate Social Responsibility (CSR)',
    description: 'Scholarship program for lower-income family students pursuing 10th Pass, 12th Pass, Graduation, and Post-Graduation.',
    amount: '₹25,000 / year',
    amountValue: 25000,
    category: 'General',
    status: 'Open',
    officialApplicationUrl: 'https://www.lichousing.com/csr-vidyadhan',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Income Certificate (< ₹3.6L)', 'Marksheet (60%+)', 'Admission Fee Receipt'],
    eligibilityCriteria: {
      minScore: 60,
      incomeLimit: 360000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 15,
      maxAge: 28,
      educationLevels: ['10th Pass', '12th Pass', 'Graduation', 'Post Graduation'],
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Medical']
    }
  },
  {
    name: 'Mahindra All India Talent Scholarship (MAITS)',
    provider: 'K. C. Mahindra Education Trust',
    ministry: 'Corporate Social Responsibility (CSR)',
    description: 'Scholarship specifically for students pursuing Diploma courses in Polytechnics across India.',
    amount: '₹10,000 / year',
    amountValue: 10000,
    category: 'General',
    status: 'Open',
    officialApplicationUrl: 'https://www.kcmet.org/maits-scholarship',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Polytechnic Admission Letter', '10th/12th Marksheet', 'Income Certificate'],
    eligibilityCriteria: {
      minScore: 60,
      incomeLimit: 300000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 15,
      maxAge: 22,
      educationLevels: ['10th Pass', '12th Pass', 'Diploma'],
      streams: ['Diploma', 'ITI']
    }
  },
  {
    name: 'Mahindra Finance Saksham Scholarship',
    provider: 'Mahindra & Mahindra Financial Services Limited',
    ministry: 'Corporate Social Responsibility (CSR)',
    description: 'Scholarship for children of commercial vehicle drivers and small farmers pursuing Higher Secondary or Graduation.',
    amount: '₹20,000 / year',
    amountValue: 20000,
    category: 'General',
    status: 'Open',
    officialApplicationUrl: 'https://www.mahindrafinance.com/csr-saksham',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Parent Commercial Driving License or Farmer Proof', 'Marksheet', 'Income Certificate'],
    eligibilityCriteria: {
      minScore: 60,
      incomeLimit: 400000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 16,
      maxAge: 24,
      educationLevels: ['10th Pass', '12th Pass', 'Graduation', 'Diploma'],
      streams: ['Science', 'Commerce', 'Arts', 'Diploma', 'ITI']
    }
  },
  {
    name: 'SBIF Asha Scholarship Program',
    provider: 'SBI Foundation (State Bank of India)',
    ministry: 'Corporate Social Responsibility (CSR)',
    description: 'Support for meritorious students from low-income households across India studying in Classes 6 to 12 or Undergraduate degrees.',
    amount: '₹15,000 / year',
    amountValue: 15000,
    category: 'General',
    status: 'Open',
    officialApplicationUrl: 'https://www.sbifoundation.in/asha-scholarship',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Income Certificate (< ₹3L)', 'Previous Year Marksheet (75%+)', 'School/College Fee Receipt'],
    eligibilityCriteria: {
      minScore: 75,
      incomeLimit: 300000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 11,
      maxAge: 24,
      educationLevels: ['Below 10th', '10th Pass', '12th Pass', 'Graduation'],
      streams: ['Science', 'Commerce', 'Arts', 'Engineering']
    }
  },
  {
    name: 'SMRITI Women in STEM Scholarship',
    provider: 'Defence Research and Development Organisation (DRDO)',
    ministry: 'Ministry of Defence',
    description: 'Promoting female talent in STEM (Science, Technology, Engineering, Mathematics) undergraduate and postgraduate programs.',
    amount: '₹100,000 / year',
    amountValue: 100000,
    category: 'Minority',
    status: 'Open',
    officialApplicationUrl: 'https://www.drdo.gov.in/careers',
    isActive: true,
    requiredDocuments: ['Aadhaar', '12th/UG Marksheet (80%+)', 'College ID', 'Income Certificate'],
    eligibilityCriteria: {
      minScore: 80,
      incomeLimit: 1000000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'Female',
      minAge: 17,
      maxAge: 28,
      educationLevels: ['12th Pass', 'Graduation', 'Post Graduation'],
      streams: ['Engineering', 'Science']
    }
  },
  {
    name: 'National Means-cum-Merit Scholarship Scheme (NMMSS)',
    provider: 'Department of School Education & Literacy, Ministry of Education',
    ministry: 'Ministry of Education',
    description: 'Scholarship awarded to meritorious students from economically weaker sections to arrest dropouts at Class 8 and encourage secondary studies.',
    amount: '₹12,000 / year',
    amountValue: 12000,
    category: 'EWS',
    status: 'Open',
    officialApplicationUrl: 'https://scholarships.gov.in',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Income Certificate (< ₹3.5L)', 'Class 7th/8th Marksheet', 'School Headmaster Verification'],
    eligibilityCriteria: {
      minScore: 55,
      incomeLimit: 350000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 13,
      maxAge: 17,
      educationLevels: ['Below 10th', '10th Pass'],
      streams: ['Science', 'Arts', 'Not Applicable']
    }
  },
  {
    name: 'Financial Assistance for Education of Children of Beedi/Cine/LSDM Workers',
    provider: 'Labour Welfare Organisation, Ministry of Labour & Employment',
    ministry: 'Ministry of Labour & Employment',
    description: 'Educational financial assistance for wards of Beedi, Cine, and Mine workers studying in Class 1 to Degree/Professional courses.',
    amount: '₹15,000 / year',
    amountValue: 15000,
    category: 'General',
    status: 'Open',
    officialApplicationUrl: 'https://scholarships.gov.in',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Labour Worker Identity Card', 'Bank Passbook', 'Marksheet'],
    eligibilityCriteria: {
      minScore: 50,
      incomeLimit: 120000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 6,
      maxAge: 25,
      educationLevels: ['Below 10th', '10th Pass', '12th Pass', 'Diploma', 'Graduation'],
      streams: ['Science', 'Commerce', 'Arts', 'Diploma', 'ITI']
    }
  },
  {
    name: 'NTPC Utility Girl Child Empowerment Scholarship',
    provider: 'NTPC Limited (National Thermal Power Corporation)',
    ministry: 'Ministry of Power',
    description: 'Empowerment grant for meritorious girl students in neighboring villages of NTPC power plants pursuing secondary & higher education.',
    amount: '₹25,000 / year',
    amountValue: 25000,
    category: 'Minority',
    status: 'Open',
    officialApplicationUrl: 'https://www.ntpc.co.in/csr-initiatives',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'Village Panchayat Residence Proof', '10th/12th Marksheet', 'Income Certificate'],
    eligibilityCriteria: {
      minScore: 65,
      incomeLimit: 500000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'Female',
      minAge: 14,
      maxAge: 23,
      educationLevels: ['10th Pass', '12th Pass', 'Graduation', 'Diploma'],
      streams: ['Science', 'Commerce', 'Arts', 'Engineering']
    }
  },
  {
    name: 'ONGC Scholarship Scheme for SC/ST Students',
    provider: 'ONGC Foundation (Oil and Natural Gas Corporation)',
    ministry: 'Ministry of Petroleum and Natural Gas',
    description: 'Scholarship awarded to economically underprivileged SC/ST students studying Engineering, MBBS, MBA, or Master in Geophysics/Geology.',
    amount: '₹48,000 / year',
    amountValue: 48000,
    category: 'SC',
    status: 'Open',
    officialApplicationUrl: 'https://www.ongcindia.com/csr-scholarship',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'SC/ST Certificate', 'Income Certificate (< ₹4.5L)', '12th Marksheet'],
    eligibilityCriteria: {
      minScore: 60,
      incomeLimit: 450000,
      categories: ['SC', 'ST'],
      states: ['All'],
      gender: 'All',
      minAge: 17,
      maxAge: 30,
      educationLevels: ['12th Pass', 'Graduation', 'Post Graduation'],
      streams: ['Engineering', 'Medical', 'Science', 'Commerce']
    }
  },
  {
    name: 'ONGC Scholarship Scheme for OBC Students',
    provider: 'ONGC Foundation (Oil and Natural Gas Corporation)',
    ministry: 'Ministry of Petroleum and Natural Gas',
    description: 'Financial aid for meritorious OBC candidates pursuing Professional degree and Master programs in approved institutes.',
    amount: '₹48,000 / year',
    amountValue: 48000,
    category: 'OBC',
    status: 'Open',
    officialApplicationUrl: 'https://www.ongcindia.com/csr-scholarship',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'OBC Non-Creamy Layer Certificate', 'Income Certificate', '12th Marksheet'],
    eligibilityCriteria: {
      minScore: 60,
      incomeLimit: 200000,
      categories: ['OBC'],
      states: ['All'],
      gender: 'All',
      minAge: 17,
      maxAge: 30,
      educationLevels: ['12th Pass', 'Graduation', 'Post Graduation'],
      streams: ['Engineering', 'Medical', 'Science', 'Commerce']
    }
  },
  {
    name: 'ONGC Scholarship Scheme for General Category (Merit)',
    provider: 'ONGC Foundation',
    ministry: 'Ministry of Petroleum and Natural Gas',
    description: 'Merit scholarship for General category EWS/Underprivileged students pursuing engineering or geology/geophysics degrees.',
    amount: '₹48,000 / year',
    amountValue: 48000,
    category: 'EWS',
    status: 'Open',
    officialApplicationUrl: 'https://www.ongcindia.com',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'EWS Certificate', 'Income Certificate (< ₹2L)', '12th Marksheet'],
    eligibilityCriteria: {
      minScore: 65,
      incomeLimit: 200000,
      categories: ['General', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 17,
      maxAge: 28,
      educationLevels: ['12th Pass', 'Graduation', 'Post Graduation'],
      streams: ['Engineering', 'Science', 'Commerce']
    }
  },
  {
    name: 'IOCL Educational Scholarship Scheme',
    provider: 'Indian Oil Corporation Limited (IOCL)',
    ministry: 'Ministry of Petroleum and Natural Gas',
    description: 'Scholarships for meritorious 10th Pass, ITI, Engineering, MBBS, and MBA students across India.',
    amount: '₹36,000 / year',
    amountValue: 36000,
    category: 'General',
    status: 'Open',
    officialApplicationUrl: 'https://www.iocl.com/csr-initiatives',
    isActive: true,
    requiredDocuments: ['Aadhaar', '10th/12th Marksheet (65%+)', 'Income Certificate', 'Bank Account Details'],
    eligibilityCriteria: {
      minScore: 65,
      incomeLimit: 1000000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 15,
      maxAge: 26,
      educationLevels: ['10th Pass', '12th Pass', 'Diploma', 'Graduation', 'Post Graduation'],
      streams: ['Engineering', 'Medical', 'Science', 'Diploma', 'ITI']
    }
  },
  {
    name: 'State Post-Matric Scholarship for EWS Candidates',
    provider: 'Department of Higher Education & State Welfare Boards',
    ministry: 'State Government Social Welfare',
    description: 'Financial aid for Economically Weaker Section (EWS) category students pursuing post-matric courses.',
    amount: '₹25,000 / year',
    amountValue: 25000,
    category: 'EWS',
    status: 'Open',
    officialApplicationUrl: 'https://scholarships.gov.in',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'EWS Certificate', 'Income Certificate (< ₹8L)', '12th Marksheet'],
    eligibilityCriteria: {
      minScore: 55,
      incomeLimit: 800000,
      categories: ['EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 16,
      maxAge: 30,
      educationLevels: ['12th Pass', 'Diploma', 'Graduation', 'Post Graduation'],
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Medical', 'Diploma']
    }
  },
  {
    name: 'DBT JRF Fellowship Program in Biotechnology',
    provider: 'Department of Biotechnology (DBT), Govt of India',
    ministry: 'Ministry of Science and Technology',
    description: 'Junior Research Fellowship for postgraduates in Biotechnology, Life Sciences, and Bio-Engineering.',
    amount: '₹444,000 / year',
    amountValue: 444000,
    category: 'General',
    status: 'Open',
    officialApplicationUrl: 'https://dbtindia.gov.in',
    isActive: true,
    requiredDocuments: ['Aadhaar', 'M.Sc/M.Tech Marksheet', 'BET Exam Scorecard', 'Research Proposal'],
    eligibilityCriteria: {
      minScore: 60,
      incomeLimit: 1500000,
      categories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      states: ['All'],
      gender: 'All',
      minAge: 21,
      maxAge: 32,
      educationLevels: ['Post Graduation', 'PhD'],
      streams: ['Science', 'Engineering']
    }
  }
];

const ensureSeedSchemes = async () => {
  try {
    for (const schemeData of MASTER_SCHEMES) {
      const slug = schemeData.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
      const shortDescription = schemeData.description.slice(0, 120) + '...';
      
      const payload = {
        ...schemeData,
        slug,
        shortDescription,
        status: schemeData.status || 'Active',
        isActive: schemeData.isActive ?? true
      };

      await Scheme.findOneAndUpdate(
        { name: schemeData.name },
        payload,
        { upsert: true, new: true, setDefaultsOnInsert: true }
      );
    }
    console.log(`✅ Master scholarship catalog (${MASTER_SCHEMES.length} schemes) active & seeded in MongoDB.`);
  } catch (err) {
    console.error('Scheme seeder error:', err.message);
  }
};

module.exports = { ensureSeedSchemes, MASTER_SCHEMES };
