const mongoose = require('mongoose');
require('dotenv').config();

const Scheme = require('./models/Scheme.model');
const User = require('./models/User.model');
const Profile = require('./models/Profile.model');
const EligibilityResult = require('./models/EligibilityResult.model');
const Notification = require('./models/Notification.model');

const schemes = [
  {
    name: 'PM National Scholarship Scheme',
    description: 'Merit-based scholarship for students pursuing UG/PG courses from central universities. Provides financial support to meritorious students from economically weaker sections.',
    category: 'General',
    ministry: 'Ministry of Education',
    amount: '₹12,000/year',
    amountValue: 12000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 17,
      maxAge: 25,
      maxAnnualIncome: 250000,
      minPercentage: 75,
      educationLevels: ['12th Pass', 'Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Medical', 'Other'],
      professions: ['Student'],
      requiredCriteria: ['Must have obtained at least 75% in the 12th Board exam', 'Must be enrolled in a full-time UG/PG program in a central university'],
      optionalCriteria: [],
      priorityCriteria: ['Priority given to BPL card holders'],
    },
    requiredDocuments: ['Income Certificate', 'Marksheet', 'Aadhaar Card'],
    applicationProcess: 'Apply through the National Scholarship Portal (scholarships.gov.in). Fill the online form, upload documents, and submit before the deadline.',
    officialLink: 'https://scholarships.gov.in',
    tags: ['merit', 'ug', 'pg', 'central'],
    isActive: true,
  },
  {
    name: 'SC/ST Post Matric Scholarship',
    description: 'Financial assistance to SC/ST students pursuing post-matric education. Covers tuition fees, maintenance allowance and other educational expenses.',
    category: 'SC',
    ministry: 'Ministry of Social Justice and Empowerment',
    amount: '₹15,000/year',
    amountValue: 15000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 14,
      maxAge: 40,
      maxAnnualIncome: 250000,
      minPercentage: 0,
      educationLevels: ['10th Pass', '12th Pass', 'Graduation', 'Post Graduation'],
      categories: ['SC', 'ST'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['All'],
      professions: ['Student'],
      requiredCriteria: ['Must possess a valid SC/ST Caste Certificate', 'Annual family income must be under ₹2.5 Lakhs'],
      optionalCriteria: [],
      priorityCriteria: ['Priority given to female candidates'],
    },
    requiredDocuments: ['Caste Certificate', 'Income Certificate', 'Marksheet'],
    applicationProcess: 'Register on NSP portal, select scheme, fill application form and upload required documents.',
    officialLink: 'https://scholarships.gov.in',
    tags: ['sc', 'st', 'post-matric', 'fees'],
    isActive: true,
  },
  {
    name: 'OBC Pre-Matric Scholarship',
    description: 'Support for OBC students enrolled in classes 1–10 from economically weaker sections. Helps reduce dropout rates among OBC students at the school level.',
    category: 'OBC',
    ministry: 'Ministry of Social Justice and Empowerment',
    amount: '₹4,000/year',
    amountValue: 4000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 5,
      maxAge: 18,
      maxAnnualIncome: 100000,
      minPercentage: 0,
      educationLevels: ['Below 10th'],
      categories: ['OBC'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Not Applicable'],
      professions: ['Student'],
      requiredCriteria: ['Must belong to OBC category', 'Must be studying in Class 1 to 10'],
      optionalCriteria: [],
      priorityCriteria: ['Priority given to families with lowest incomes'],
    },
    requiredDocuments: ['Caste Certificate', 'Income Certificate', 'Aadhaar Card'],
    applicationProcess: 'Apply through the state scholarship portal or National Scholarship Portal before the deadline.',
    officialLink: 'https://scholarships.gov.in',
    tags: ['obc', 'pre-matric', 'school'],
    isActive: true,
  },
  {
    name: 'Central Sector Scholarship for College Students',
    description: 'For students in the top 20 percentile of their 12th board pursuing higher education. One of India\'s most prestigious merit scholarships.',
    category: 'General',
    ministry: 'Ministry of Education',
    amount: '₹20,000/year',
    amountValue: 20000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 17,
      maxAge: 22,
      maxAnnualIncome: 450000,
      minPercentage: 80,
      educationLevels: ['12th Pass', 'Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Medical', 'Diploma'],
      professions: ['Student'],
      requiredCriteria: ['Must have scored 80% or above in 12th board', 'Family annual income must not exceed ₹4.5 Lakhs'],
      optionalCriteria: [],
      priorityCriteria: [],
    },
    requiredDocuments: ['Marksheet', 'Income Certificate', 'Aadhaar Card'],
    applicationProcess: 'Apply on NSP within 6 months of admission. Renewal available each year based on academic performance.',
    officialLink: 'https://scholarships.gov.in',
    tags: ['merit', 'ug', 'prestigious'],
    isActive: true,
  },
  {
    name: 'INSPIRE Scholarship for Higher Education',
    description: "DST's flagship scholarship for students pursuing Natural Sciences at UG level. Encourages talented students to pursue careers in science research.",
    category: 'General',
    ministry: 'Department of Science & Technology',
    amount: '₹80,000/year',
    amountValue: 80000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 17,
      maxAge: 22,
      maxAnnualIncome: 9999999,
      minPercentage: 85,
      educationLevels: ['12th Pass', 'Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Science', 'Engineering'],
      professions: ['Student'],
      requiredCriteria: ['Must be enrolled in basic/natural science courses (BSc, BS)', 'Must possess marks in top 1% of the respective board exam'],
      optionalCriteria: [],
      priorityCriteria: [],
    },
    requiredDocuments: ['Marksheet', 'Aadhaar Card'],
    applicationProcess: 'Apply through DST INSPIRE portal. Requires being in top 1% of respective board examination.',
    officialLink: 'https://online-inspire.gov.in',
    tags: ['science', 'dst', 'bsc', 'research', 'merit'],
    isActive: true,
  },
  {
    name: 'Pragati Scholarship for Girl Students',
    description: 'AICTE scholarship exclusively for girl students pursuing technical education (engineering/MBA) to promote gender diversity in STEM.',
    category: 'General',
    ministry: 'All India Council for Technical Education',
    amount: '₹50,000/year',
    amountValue: 50000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 17,
      maxAge: 30,
      maxAnnualIncome: 800000,
      minPercentage: 0,
      educationLevels: ['12th Pass', 'Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['Female'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Engineering', 'Medical', 'Diploma'],
      professions: ['Student'],
      requiredCriteria: ['Must be female', 'Enrolled in an AICTE approved college for Engineering or Professional Degree'],
      optionalCriteria: [],
      priorityCriteria: ['Priority given to disabled girls'],
    },
    requiredDocuments: ['Income Certificate', 'Aadhaar Card', 'Marksheet'],
    applicationProcess: 'Apply on AICTE portal. One girl per family is eligible. Tuition fee waiver + cash incentive.',
    officialLink: 'https://aicte-pragati-saksham-gov.in',
    tags: ['girls', 'stem', 'engineering', 'female'],
    isActive: true,
  },
  {
    name: 'National Means-cum-Merit Scholarship',
    description: 'Scholarship for meritorious students of economically weaker sections to arrest their dropout rate at Class VIII and continue until Class XII.',
    category: 'General',
    ministry: 'Ministry of Education',
    amount: '₹12,000/year',
    amountValue: 12000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 12,
      maxAge: 18,
      maxAnnualIncome: 150000,
      minPercentage: 55,
      educationLevels: ['Below 10th'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Not Applicable'],
      professions: ['Student'],
      requiredCriteria: ['Must pass the state level NMMS entrance examination', 'Must study in local government/aided school'],
      optionalCriteria: [],
      priorityCriteria: ['Priority for BPL families'],
    },
    requiredDocuments: ['Income Certificate', 'Marksheet', 'Aadhaar Card'],
    applicationProcess: 'Students in Class VIII need to appear for the NMMS examination conducted by states/UTs.',
    officialLink: 'https://scholarships.gov.in',
    tags: ['school', 'means-cum-merit', 'dropout-prevention'],
    isActive: true,
  },
  {
    name: 'Ishan Uday Special Scholarship – North East',
    description: 'Special scholarship for students from North East region pursuing general degree courses to promote higher education in the region.',
    category: 'General',
    ministry: 'University Grants Commission (UGC)',
    amount: '₹75,600/year',
    amountValue: 75600,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 17,
      maxAge: 30,
      maxAnnualIncome: 450000,
      minPercentage: 0,
      educationLevels: ['12th Pass', 'Graduation'],
      categories: ['All'],
      states: ['Assam', 'Meghalaya', 'Manipur', 'Mizoram', 'Nagaland', 'Tripura', 'Arunachal Pradesh', 'Sikkim'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Medical', 'Diploma'],
      professions: ['Student'],
      requiredCriteria: ['Must be a permanent resident of North Eastern states', 'Family income must be under ₹4.5 Lakhs'],
      optionalCriteria: [],
      priorityCriteria: ['Priority given to rural and farming background families'],
    },
    requiredDocuments: ['Domicile Certificate', 'Income Certificate', 'Aadhaar Card', 'Marksheet'],
    applicationProcess: 'Apply on UGC Ishan Uday portal. Preference given to students from rural and remote areas.',
    officialLink: 'https://ugc.ac.in',
    tags: ['north-east', 'regional', 'ugc'],
    isActive: true,
  },
  {
    name: 'Minority Scholarship Scheme',
    description: 'Post-matric scholarship for students belonging to minority communities (Muslim, Christian, Sikh, Buddhist, Zoroastrian, etc.) to pursue higher education.',
    category: 'Minority',
    ministry: 'Ministry of Minority Affairs',
    amount: '₹25,000/year',
    amountValue: 25000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 14,
      maxAge: 40,
      maxAnnualIncome: 300000,
      minPercentage: 0,
      educationLevels: ['10th Pass', '12th Pass', 'Graduation', 'Post Graduation'],
      categories: ['Minority'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Medical', 'Diploma'],
      professions: ['Student'],
      requiredCriteria: ['Must belong to recognized minority community', 'Annual family income must not exceed ₹3 Lakhs', 'Must be enrolled in full-time education'],
      optionalCriteria: [],
      priorityCriteria: ['Priority given to girls and persons with disabilities'],
    },
    requiredDocuments: ['Minority Certificate', 'Income Certificate', 'Marksheet', 'Aadhaar Card'],
    applicationProcess: 'Register on NSP portal, fill form with minority certification and upload required documents.',
    officialLink: 'https://scholarships.gov.in',
    tags: ['minority', 'post-matric', 'inclusive'],
    isActive: true,
  },
  {
    name: 'Scholarship for PwD (Persons with Disability)',
    description: 'Financial assistance for persons with disabilities pursuing higher education at UG/PG level. Includes provision for care attendant and other support.',
    category: 'General',
    ministry: 'Ministry of Social Justice & Empowerment',
    amount: '₹30,000/year + ₹15,000 for attendant',
    amountValue: 45000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 17,
      maxAge: 35,
      maxAnnualIncome: 500000,
      minPercentage: 0,
      educationLevels: ['12th Pass', 'Graduation', 'Post Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: true,
      bplRequired: false,
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Medical', 'Law', 'Management'],
      professions: ['Student'],
      requiredCriteria: ['Must be certified with at least 40% disability', 'Must be enrolled in UG/PG course in recognized institution'],
      optionalCriteria: [],
      priorityCriteria: ['Additional support for multiple disabilities'],
    },
    requiredDocuments: ['Disability Certificate', 'Income Certificate', 'Aadhaar Card', 'Marksheet'],
    applicationProcess: 'Apply on NSP with disability certificate. Additional funds available for care attendant if required.',
    officialLink: 'https://scholarships.gov.in',
    tags: ['disability', 'pwd', 'inclusive', 'support'],
    isActive: true,
  },
  {
    name: 'Rajiv Gandhi National Fellowship (UGC)',
    description: 'Fellowship for students pursuing PG and doctoral programs in social science and humanities. Encourages research in these critical fields.',
    category: 'General',
    ministry: 'University Grants Commission',
    amount: '₹34,000 - ₹44,000/month',
    amountValue: 500000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 22,
      maxAge: 45,
      maxAnnualIncome: 9999999,
      minPercentage: 0,
      educationLevels: ['Graduation', 'Post Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Arts', 'Social Science', 'Humanities'],
      professions: ['Student', 'Researcher'],
      requiredCriteria: ['Must be Indian citizen', 'Pursuing Masters/PhD in eligible disciplines', 'Minimum 55% in graduation'],
      optionalCriteria: [],
      priorityCriteria: ['Priority for SC/ST candidates'],
    },
    requiredDocuments: ['Marksheet', 'Aadhaar Card', 'University Admission Letter'],
    applicationProcess: 'Apply to UGC PFMS portal. Selection through national merit-based examination.',
    officialLink: 'https://ugcnfp.gov.in',
    tags: ['fellowship', 'pg', 'research', 'humanities'],
    isActive: true,
  },
  {
    name: 'Vidyasaarathi Fellowship - Vedavati Foundation (NGO)',
    description: 'NGO-funded scholarship for underprivileged girls pursuing engineering. Includes mentorship and career guidance alongside financial support.',
    category: 'General',
    ministry: 'Vedavati Foundation (NGO)',
    amount: '₹45,000/year + mentorship',
    amountValue: 45000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 17,
      maxAge: 25,
      maxAnnualIncome: 250000,
      minPercentage: 65,
      educationLevels: ['12th Pass', 'Graduation'],
      categories: ['All'],
      states: ['Maharashtra', 'Karnataka', 'Tamil Nadu', 'Telangana'],
      genders: ['Female'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Engineering', 'Technology'],
      professions: ['Student'],
      requiredCriteria: ['Must be a girl from low-income family', 'Minimum 65% in 12th', 'Pursuing engineering degree'],
      optionalCriteria: [],
      priorityCriteria: ['First-generation learners preferred'],
    },
    requiredDocuments: ['Income Certificate', 'Marksheet', 'Aadhaar Card', 'College Admission Letter'],
    applicationProcess: 'Apply directly to Vedavati Foundation. Includes personality development and internship opportunities.',
    officialLink: 'https://vedavati-foundation.org',
    tags: ['ngo', 'girls', 'engineering', 'mentorship'],
    isActive: true,
  },
  {
    name: 'Teach India Scholarship - The Times of India (CSR)',
    description: 'CSR initiative supporting rural and economically disadvantaged students pursuing graduation. Focus on merging education with community service.',
    category: 'General',
    ministry: 'The Times of India - Corporate Social Responsibility',
    amount: '₹50,000/year',
    amountValue: 50000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 25,
      maxAnnualIncome: 200000,
      minPercentage: 50,
      educationLevels: ['12th Pass', 'Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Science', 'Commerce', 'Arts'],
      professions: ['Student'],
      requiredCriteria: ['Must be from rural area or economically weaker section', 'Currently studying first or second year UG'],
      optionalCriteria: [],
      priorityCriteria: ['Community involvement appreciated'],
    },
    requiredDocuments: ['Income Certificate', 'Aadhaar Card', 'Marksheet', 'Domicile Certificate'],
    applicationProcess: 'Apply on Teach India portal. Requires community service engagement report.',
    officialLink: 'https://teachindia.times.indiatimes.com',
    tags: ['csr', 'rural', 'community', 'ngo'],
    isActive: true,
  },
  {
    name: 'AICTE GATE Scholarship for PG Studies',
    description: 'Scholarship for GATE-qualified students pursuing MTech and MBA from AICTE-approved institutions. Merit-based with performance incentives.',
    category: 'General',
    ministry: 'All India Council for Technical Education',
    amount: '₹60,000 - ₹72,000/year',
    amountValue: 70000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 21,
      maxAge: 35,
      maxAnnualIncome: 1000000,
      minPercentage: 0,
      educationLevels: ['Graduation', 'Post Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Engineering', 'Technology', 'Management'],
      professions: ['Student'],
      requiredCriteria: ['Must be GATE qualified', 'Enrolled in AICTE-approved MTech or MBA program'],
      optionalCriteria: [],
      priorityCriteria: [],
    },
    requiredDocuments: ['GATE Score Card', 'Aadhaar Card', 'University Admission Letter'],
    applicationProcess: 'Apply to AICTE after GATE score publication. Automatic based on GATE rank and college fee.',
    officialLink: 'https://aicte-india.org',
    tags: ['gate', 'postgrad', 'technical', 'mtech'],
    isActive: true,
  },
  {
    name: 'Dr. Ambedkar Post Matric Scholarship Scheme',
    description: 'Post-matric scholarship for SC/ST students pursuing courses after 10th standard. Major government flagship scheme with comprehensive support.',
    category: 'SC',
    ministry: 'Ministry of Social Justice & Empowerment',
    amount: '₹36,000/year + fees reimbursement',
    amountValue: 36000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 14,
      maxAge: 45,
      maxAnnualIncome: 250000,
      minPercentage: 0,
      educationLevels: ['10th Pass', '12th Pass', 'Graduation', 'Post Graduation', 'Diploma', 'ITI'],
      categories: ['SC', 'ST'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['All'],
      professions: ['Student'],
      requiredCriteria: ['Valid SC/ST caste certificate', 'Enrolled in post-10th course', 'Annual income limit ₹2.5 Lakhs'],
      optionalCriteria: [],
      priorityCriteria: ['Female applicants given 15% higher assistance'],
    },
    requiredDocuments: ['Caste Certificate', 'Income Certificate', 'Aadhaar Card', 'Marksheet'],
    applicationProcess: 'Register on NSP. Application verified by state authorities. Direct fund transfer to bank account.',
    officialLink: 'https://scholarships.gov.in',
    tags: ['sc', 'st', 'post-matric', 'flagship'],
    isActive: true,
  },
  {
    name: 'Maulana Azad Scholarship (Muslims)',
    description: 'Specialized scholarship for Muslim students pursuing professional courses (engineering, medicine, law). Promotes higher education among Muslim community.',
    category: 'Minority',
    ministry: 'Ministry of Minority Affairs',
    amount: '₹35,000/year + fees',
    amountValue: 35000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 17,
      maxAge: 30,
      maxAnnualIncome: 400000,
      minPercentage: 60,
      educationLevels: ['12th Pass', 'Graduation'],
      categories: ['Minority'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Engineering', 'Medical', 'Law', 'Science'],
      professions: ['Student'],
      requiredCriteria: ['Muslim student', 'Enrolled in professional course', 'Income limit ₹4 Lakhs'],
      optionalCriteria: [],
      priorityCriteria: ['Priority for girls and rural students'],
    },
    requiredDocuments: ['Affidavit of Muslim Religion', 'Income Certificate', 'Marksheet', 'Aadhaar Card'],
    applicationProcess: 'Apply on Ministry of Minority Affairs portal. Requires religious certification as per government guidelines.',
    officialLink: 'https://moma.gov.in',
    tags: ['minority', 'muslim', 'professional'],
    isActive: true,
  },
  {
    name: 'Tata Trusts Leadership Scholarship Program',
    description: 'Prestigious scholarship from Tata Trusts for exceptionally talented students from economically disadvantaged backgrounds. Includes leadership development.',
    category: 'General',
    ministry: 'Tata Trusts (NGO/CSR)',
    amount: '₹100,000/year',
    amountValue: 100000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 16,
      maxAge: 28,
      maxAnnualIncome: 300000,
      minPercentage: 70,
      educationLevels: ['12th Pass', 'Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Science', 'Commerce', 'Engineering', 'Management'],
      professions: ['Student'],
      requiredCriteria: ['Demonstrated exceptional talent or potential', 'From economically weaker background', 'Enrollment in recognized institution'],
      optionalCriteria: [],
      priorityCriteria: ['Leadership qualities', 'Community engagement', 'First-generation students'],
    },
    requiredDocuments: ['Income Certificate', 'Marksheet', 'Essay on Leadership Vision', 'Recommendation Letters'],
    applicationProcess: 'Apply through Tata Trusts website. Includes interviews, assessment, leadership training, and mentorship.',
    officialLink: 'https://www.tata-trusts.org',
    tags: ['csr', 'leadership', 'prestigious', 'holistic'],
    isActive: true,
  },
  {
    name: 'Armed Forces Flag Day Scholarship',
    description: 'Scholarship for children of armed forces personnel (servicemen, veterans, deceased). Supports continuation of education after school/college.',
    category: 'General',
    ministry: 'Ministry of Defence',
    amount: '₹40,000/year',
    amountValue: 40000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 17,
      maxAge: 30,
      maxAnnualIncome: 600000,
      minPercentage: 50,
      educationLevels: ['12th Pass', 'Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['All'],
      professions: ['Student', 'Military Family'],
      requiredCriteria: ['Child of armed forces personnel (serving/retired/deceased)', 'Pursuing UG/PG course'],
      optionalCriteria: [],
      priorityCriteria: ['Children of martyred soldiers given highest priority'],
    },
    requiredDocuments: ['Service/Pension Certificate', 'Aadhaar Card', 'Marksheet', 'Income Certificate'],
    applicationProcess: 'Apply to Armed Forces Fund Board. Verification through Ministry of Defence records.',
    officialLink: 'https://www.indianarmy.nic.in',
    tags: ['armed forces', 'military', 'veteran', 'family'],
    isActive: true,
  },
  {
    name: 'Deshmukh Foundation Scholarship - Commerce & Accounts',
    description: 'NGO scholarship specifically for commerce and accounts students from low-income families. Encourages finance and accounting professionals.',
    category: 'General',
    ministry: 'Deshmukh Foundation (NGO)',
    amount: '₹30,000/year',
    amountValue: 30000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 17,
      maxAge: 25,
      maxAnnualIncome: 250000,
      minPercentage: 55,
      educationLevels: ['12th Pass', 'Graduation'],
      categories: ['All'],
      states: ['Maharashtra', 'Gujarat', 'Karnataka'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Commerce', 'Management'],
      professions: ['Student'],
      requiredCriteria: ['Pursuing BCom or related commerce degree', 'Family annual income under ₹2.5 Lakhs'],
      optionalCriteria: [],
      priorityCriteria: ['Girls and SC/ST students given 20% additional preference'],
    },
    requiredDocuments: ['Income Certificate', 'Marksheet', 'College Admission Letter', 'Aadhaar Card'],
    applicationProcess: 'Apply to Deshmukh Foundation. Scholarship disbursed after college confirmation.',
    officialLink: 'https://deshmukh-foundation.org',
    tags: ['ngo', 'commerce', 'accounts', 'regional'],
    isActive: true,
  },
  {
    name: 'ICMR SRF - Biomedical Research Fellowship',
    description: 'Fellowship for students pursuing biomedical research, microbiology, and health sciences. Direct pathway to research career in medical field.',
    category: 'General',
    ministry: 'Indian Council of Medical Research',
    amount: '₹31,000/month',
    amountValue: 372000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 21,
      maxAge: 40,
      maxAnnualIncome: 9999999,
      minPercentage: 0,
      educationLevels: ['Post Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Medical', 'Science', 'Biotechnology'],
      professions: ['Student', 'Researcher'],
      requiredCriteria: ['Masters degree in life sciences/medical field', 'Research proposal in biomedical sciences'],
      optionalCriteria: [],
      priorityCriteria: [],
    },
    requiredDocuments: ['Marksheet', 'Research Proposal', 'Aadhaar Card', 'Institutional Affiliation Letter'],
    applicationProcess: 'Apply to ICMR-SRF portal. Selection through research proposal evaluation and interview.',
    officialLink: 'https://www.icmr.gov.in',
    tags: ['research', 'medical', 'fellowship', 'biomedical'],
    isActive: true,
  },
  {
    name: 'Ramakrishna Mission Scholarship (All India)',
    description: 'Scholarship from a leading spiritual organization for meritorious and deserving students across India. Holistic support with character building.',
    category: 'General',
    ministry: 'Ramakrishna Mission (NGO/Spiritual Organization)',
    amount: '₹35,000/year',
    amountValue: 35000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 16,
      maxAge: 30,
      maxAnnualIncome: 300000,
      minPercentage: 60,
      educationLevels: ['12th Pass', 'Graduation', 'Post Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['All'],
      professions: ['Student'],
      requiredCriteria: ['Pursuing any full-time education', 'Good moral character', 'Family income limit ₹3 Lakhs'],
      optionalCriteria: [],
      priorityCriteria: ['Preference to those showing social commitment'],
    },
    requiredDocuments: ['Income Certificate', 'Marksheet', 'Character Certificate', 'Aadhaar Card'],
    applicationProcess: 'Apply to nearest Ramakrishna Mission center or headquarters. Includes value-based education and mentoring.',
    officialLink: 'https://www.ramakrishnamission.org',
    tags: ['ngo', 'spiritual', 'holistic', 'character'],
    isActive: true,
  },
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ Connected to MongoDB');

    // Clear existing data
    await Scheme.deleteMany({});
    await EligibilityResult.deleteMany({});
    await Notification.deleteMany({});
    console.log('🗑️  Cleared existing DB data');

    // Insert schemes
    const created = await Scheme.insertMany(schemes);
    console.log(`✅ Seeded ${created.length} scholarship schemes`);

    // Create a demo admin user
    await User.deleteMany({ email: 'admin@uss.gov.in' });
    const admin = await User.create({
      name: 'USS Admin',
      email: 'admin@uss.gov.in',
      password: 'admin@123',
      role: 'admin',
      isEmailVerified: true,
    });
    console.log(`✅ Admin user created: admin@uss.gov.in / admin@123`);

    // Demo student
    await User.deleteMany({ email: 'student@demo.com' });
    const student = await User.create({
      name: 'Priya Sharma',
      email: 'student@demo.com',
      password: 'demo@123',
      role: 'student',
      isEmailVerified: true,
    });

    await Profile.deleteMany({ user: student._id });
    await Profile.create({
      user: student._id,
      fullName: 'Priya Sharma',
      age: 21,
      gender: 'Female',
      state: 'Maharashtra',
      district: 'Mumbai',
      mobileNumber: '9876543210',
      email: 'student@demo.com',
      educationLevel: '12th Pass',
      stream: 'Science',
      collegeName: 'St. Xavier\'s College',
      cgpaOrPercentage: 88,
      currentYearOrSemester: '1st Year',
      profession: 'Student',
      annualFamilyIncome: 150000, // set below PM National limit
      bplStatus: false,
      category: 'General',
      minorityStatus: false,
      disabilityStatus: false,
      documentUploads: {
        aadhaar: 'https://uss-documents.s3.amazonaws.com/aadhaar_priya.pdf',
        incomeCertificate: '', // initially empty for simulation
        casteCertificate: '',
        domicile: 'https://uss-documents.s3.amazonaws.com/domicile_priya.pdf',
        marksheet: 'https://uss-documents.s3.amazonaws.com/marksheet_priya.pdf',
        disabilityCertificate: ''
      }
    });
    console.log(`✅ Demo student created: student@demo.com / demo@123`);

    // Create initial notification
    await Notification.create({
      user: student._id,
      title: '👋 Welcome to USS Platform',
      message: 'Keep your student profile updated and upload documents to verify scholarship match rates!',
      type: 'info'
    });
    console.log(`✅ Initial welcome notification seeded`);

    console.log('\n🎉 Database seeded successfully!');
    console.log('─────────────────────────────────────');
    console.log('Admin:   admin@uss.gov.in  /  admin@123');
    console.log('Student: student@demo.com  /  demo@123');
    console.log('─────────────────────────────────────');

    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error.message);
    process.exit(1);
  }
};

seedDB();
