const mongoose = require('mongoose');
require('dotenv').config();

const Scheme = require('./models/Scheme.model');
const User = require('./models/User.model');
const Profile = require('./models/Profile.model');
const EligibilityResult = require('./models/EligibilityResult.model');
const Notification = require('./models/Notification.model');

const schemes = [
  {
    name: 'PM National Scholarship Scheme',
    description: 'Merit-based scholarship for students pursuing UG/PG courses from central universities. Provides financial support to meritorious students from economically weaker sections.',
    category: 'General',
    ministry: 'Ministry of Education',
    amount: '₹12,000/year',
    amountValue: 12000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 17,
      maxAge: 25,
      maxAnnualIncome: 250000,
      minPercentage: 75,
      educationLevels: ['12th Pass', 'Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Medical', 'Other'],
      professions: ['Student'],
      requiredCriteria: ['Must have obtained at least 75% in the 12th Board exam', 'Must be enrolled in a full-time UG/PG program in a central university'],
      optionalCriteria: [],
      priorityCriteria: ['Priority given to BPL card holders'],
    },
    requiredDocuments: ['Income Certificate', 'Marksheet', 'Aadhaar Card'],
    applicationProcess: 'Apply through the National Scholarship Portal (scholarships.gov.in). Fill the online form, upload documents, and submit before the deadline.',
    officialLink: 'https://scholarships.gov.in',
    tags: ['merit', 'ug', 'pg', 'central'],
    isActive: true,
  },
  {
    name: 'SC/ST Post Matric Scholarship',
    description: 'Financial assistance to SC/ST students pursuing post-matric education. Covers tuition fees, maintenance allowance and other educational expenses.',
    category: 'SC',
    ministry: 'Ministry of Social Justice and Empowerment',
    amount: '₹15,000/year',
    amountValue: 15000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 14,
      maxAge: 40,
      maxAnnualIncome: 250000,
      minPercentage: 0,
      educationLevels: ['10th Pass', '12th Pass', 'Graduation', 'Post Graduation'],
      categories: ['SC', 'ST'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['All'],
      professions: ['Student'],
      requiredCriteria: ['Must possess a valid SC/ST Caste Certificate', 'Annual family income must be under ₹2.5 Lakhs'],
      optionalCriteria: [],
      priorityCriteria: ['Priority given to female candidates'],
    },
    requiredDocuments: ['Caste Certificate', 'Income Certificate', 'Marksheet'],
    applicationProcess: 'Register on NSP portal, select scheme, fill application form and upload required documents.',
    officialLink: 'https://scholarships.gov.in',
    tags: ['sc', 'st', 'post-matric', 'fees'],
    isActive: true,
  },
  {
    name: 'OBC Pre-Matric Scholarship',
    description: 'Support for OBC students enrolled in classes 1–10 from economically weaker sections. Helps reduce dropout rates among OBC students at the school level.',
    category: 'OBC',
    ministry: 'Ministry of Social Justice and Empowerment',
    amount: '₹4,000/year',
    amountValue: 4000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 5,
      maxAge: 18,
      maxAnnualIncome: 100000,
      minPercentage: 0,
      educationLevels: ['Below 10th'],
      categories: ['OBC'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Not Applicable'],
      professions: ['Student'],
      requiredCriteria: ['Must belong to OBC category', 'Must be studying in Class 1 to 10'],
      optionalCriteria: [],
      priorityCriteria: ['Priority given to families with lowest incomes'],
    },
    requiredDocuments: ['Caste Certificate', 'Income Certificate', 'Aadhaar Card'],
    applicationProcess: 'Apply through the state scholarship portal or National Scholarship Portal before the deadline.',
    officialLink: 'https://scholarships.gov.in',
    tags: ['obc', 'pre-matric', 'school'],
    isActive: true,
  },
  {
    name: 'Central Sector Scholarship for College Students',
    description: 'For students in the top 20 percentile of their 12th board pursuing higher education. One of India\'s most prestigious merit scholarships.',
    category: 'General',
    ministry: 'Ministry of Education',
    amount: '₹20,000/year',
    amountValue: 20000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 17,
      maxAge: 22,
      maxAnnualIncome: 450000,
      minPercentage: 80,
      educationLevels: ['12th Pass', 'Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Medical', 'Diploma'],
      professions: ['Student'],
      requiredCriteria: ['Must have scored 80% or above in 12th board', 'Family annual income must not exceed ₹4.5 Lakhs'],
      optionalCriteria: [],
      priorityCriteria: [],
    },
    requiredDocuments: ['Marksheet', 'Income Certificate', 'Aadhaar Card'],
    applicationProcess: 'Apply on NSP within 6 months of admission. Renewal available each year based on academic performance.',
    officialLink: 'https://scholarships.gov.in',
    tags: ['merit', 'ug', 'prestigious'],
    isActive: true,
  },
  {
    name: 'INSPIRE Scholarship for Higher Education',
    description: "DST's flagship scholarship for students pursuing Natural Sciences at UG level. Encourages talented students to pursue careers in science research.",
    category: 'General',
    ministry: 'Department of Science & Technology',
    amount: '₹80,000/year',
    amountValue: 80000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 17,
      maxAge: 22,
      maxAnnualIncome: 9999999,
      minPercentage: 85,
      educationLevels: ['12th Pass', 'Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Science', 'Engineering'],
      professions: ['Student'],
      requiredCriteria: ['Must be enrolled in basic/natural science courses (BSc, BS)', 'Must possess marks in top 1% of the respective board exam'],
      optionalCriteria: [],
      priorityCriteria: [],
    },
    requiredDocuments: ['Marksheet', 'Aadhaar Card'],
    applicationProcess: 'Apply through DST INSPIRE portal. Requires being in top 1% of respective board examination.',
    officialLink: 'https://online-inspire.gov.in',
    tags: ['science', 'dst', 'bsc', 'research', 'merit'],
    isActive: true,
  },
  {
    name: 'Pragati Scholarship for Girl Students',
    description: 'AICTE scholarship exclusively for girl students pursuing technical education (engineering/MBA) to promote gender diversity in STEM.',
    category: 'General',
    ministry: 'All India Council for Technical Education',
    amount: '₹50,000/year',
    amountValue: 50000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 17,
      maxAge: 30,
      maxAnnualIncome: 800000,
      minPercentage: 0,
      educationLevels: ['12th Pass', 'Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['Female'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Engineering', 'Medical', 'Diploma'],
      professions: ['Student'],
      requiredCriteria: ['Must be female', 'Enrolled in an AICTE approved college for Engineering or Professional Degree'],
      optionalCriteria: [],
      priorityCriteria: ['Priority given to disabled girls'],
    },
    requiredDocuments: ['Income Certificate', 'Aadhaar Card', 'Marksheet'],
    applicationProcess: 'Apply on AICTE portal. One girl per family is eligible. Tuition fee waiver + cash incentive.',
    officialLink: 'https://aicte-pragati-saksham-gov.in',
    tags: ['girls', 'stem', 'engineering', 'female'],
    isActive: true,
  },
  {
    name: 'National Means-cum-Merit Scholarship',
    description: 'Scholarship for meritorious students of economically weaker sections to arrest their dropout rate at Class VIII and continue until Class XII.',
    category: 'General',
    ministry: 'Ministry of Education',
    amount: '₹12,000/year',
    amountValue: 12000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 12,
      maxAge: 18,
      maxAnnualIncome: 150000,
      minPercentage: 55,
      educationLevels: ['Below 10th'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Not Applicable'],
      professions: ['Student'],
      requiredCriteria: ['Must pass the state level NMMS entrance examination', 'Must study in local government/aided school'],
      optionalCriteria: [],
      priorityCriteria: ['Priority for BPL families'],
    },
    requiredDocuments: ['Income Certificate', 'Marksheet', 'Aadhaar Card'],
    applicationProcess: 'Students in Class VIII need to appear for the NMMS examination conducted by states/UTs.',
    officialLink: 'https://scholarships.gov.in',
    tags: ['school', 'means-cum-merit', 'dropout-prevention'],
    isActive: true,
  },
  {
    name: 'Ishan Uday Special Scholarship – North East',
    description: 'Special scholarship for students from North East region pursuing general degree courses to promote higher education in the region.',
    category: 'General',
    ministry: 'University Grants Commission (UGC)',
    amount: '₹75,600/year',
    amountValue: 75600,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 17,
      maxAge: 30,
      maxAnnualIncome: 450000,
      minPercentage: 0,
      educationLevels: ['12th Pass', 'Graduation'],
      categories: ['All'],
      states: ['Assam', 'Meghalaya', 'Manipur', 'Mizoram', 'Nagaland', 'Tripura', 'Arunachal Pradesh', 'Sikkim'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Medical', 'Diploma'],
      professions: ['Student'],
      requiredCriteria: ['Must be a permanent resident of North Eastern states', 'Family income must be under ₹4.5 Lakhs'],
      optionalCriteria: [],
      priorityCriteria: ['Priority given to rural and farming background families'],
    },
    requiredDocuments: ['Domicile Certificate', 'Income Certificate', 'Aadhaar Card', 'Marksheet'],
    applicationProcess: 'Apply on UGC Ishan Uday portal. Preference given to students from rural and remote areas.',
    officialLink: 'https://ugc.ac.in',
    tags: ['north-east', 'regional', 'ugc'],
    isActive: true,
  },
  {
    name: 'Tata Capital Pankh Scholarship',
    description: 'Corporate CSR initiative by Tata Capital to support higher education of students from low-income families through financial aid.',
    category: 'General',
    ministry: 'Tata Capital CSR Foundation',
    amount: '₹20,000/year',
    amountValue: 20000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 16,
      maxAge: 25,
      maxAnnualIncome: 400000,
      minPercentage: 60,
      educationLevels: ['12th Pass', 'Graduation', 'Post Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Medical', 'Other'],
      professions: ['Student'],
      requiredCriteria: ['Must have scored 60% or above in previous academic class', 'Must be enrolled in a recognised college/university in India'],
      optionalCriteria: [],
      priorityCriteria: [],
    },
    requiredDocuments: ['Income Certificate', 'Marksheet', 'Aadhaar Card'],
    applicationProcess: 'Submit online application form via Buddy4Study portal, upload income details and marksheets.',
    officialLink: 'https://www.buddy4study.com/page/tata-capital-pankh-scholarship',
    tags: ['tata', 'corporate', 'ug', 'pg'],
    isActive: true,
  },
  {
    name: 'HDFC Badhte Kadam Scholarship',
    description: 'HDFC Bank initiative offering financial aid to students from class 11 up to professional UG and PG degrees, with focus on girl students and students in distress.',
    category: 'General',
    ministry: 'HDFC Bank CSR Department',
    amount: '₹1,00,000/year',
    amountValue: 100000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 15,
      maxAge: 28,
      maxAnnualIncome: 600000,
      minPercentage: 70,
      educationLevels: ['12th Pass', 'Graduation', 'Post Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['All'],
      professions: ['Student'],
      requiredCriteria: ['Must be studying in 11th, 12th, or pursuing UG/PG courses', 'Must have secured at least 70% in the previous class'],
      optionalCriteria: [],
      priorityCriteria: ['Special weightage to girls, single-parent kids, and children from covid affected families'],
    },
    requiredDocuments: ['Income Certificate', 'Marksheet', 'Aadhaar Card'],
    applicationProcess: 'Apply online on HDFC CSR site or partner NGO portals. Complete profile evaluation and brief phone screening.',
    officialLink: 'https://www.hdfcbank.com/personal/about-us/corporate-social-responsibility',
    tags: ['hdfc', 'corporate', 'high-value'],
    isActive: true,
  },
  {
    name: 'Aditya Birla Capital COVID Support Scholarship',
    description: 'Special scheme by Aditya Birla Capital Foundation to support children who have lost one or both parents to COVID-19, ensuring continuity of education.',
    category: 'General',
    ministry: 'Aditya Birla Capital Foundation',
    amount: '₹30,000/year',
    amountValue: 30000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 6,
      maxAge: 24,
      maxAnnualIncome: 600000,
      minPercentage: 0,
      educationLevels: ['Below 10th', '10th Pass', '12th Pass', 'Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['All'],
      professions: ['Student'],
      requiredCriteria: ['Must have lost one or both parents due to COVID-19 pandemic', 'Currently enrolled in school or undergraduate course'],
      optionalCriteria: [],
      priorityCriteria: [],
    },
    requiredDocuments: ['Death Certificate of Parent', 'Aadhaar Card', 'Marksheet'],
    applicationProcess: 'Register on CSR Portal, upload proof of covid dependency/death certificate, fee receipts and submit.',
    officialLink: 'https://www.adityabirlacapital.com',
    tags: ['aditya-birla', 'distress', 'covid-support'],
    isActive: true,
  },
  {
    name: 'LIC Golden Jubilee Scholarship',
    description: 'Scholarship scheme established by LIC of India for students from economically weaker sections pursuing vocational, technical or higher secondary courses.',
    category: 'General',
    ministry: 'Life Insurance Corporation of India',
    amount: '₹20,000/year',
    amountValue: 20000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 16,
      maxAge: 22,
      maxAnnualIncome: 250000,
      minPercentage: 60,
      educationLevels: ['12th Pass', 'Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Medical', 'Diploma'],
      professions: ['Student'],
      requiredCriteria: ['Scored 60% or above in 12th standard (or equivalent)', 'Family annual income must not exceed 2.5 Lakhs'],
      optionalCriteria: [],
      priorityCriteria: [],
    },
    requiredDocuments: ['Marksheet', 'Income Certificate', 'Aadhaar Card'],
    applicationProcess: 'Apply online through LIC corporate portal during the active window (usually July to September).',
    officialLink: 'https://licindia.in',
    tags: ['lic', 'corporate', 'ug', 'diploma'],
    isActive: true,
  },
  {
    name: "L'Oréal India For Young Women in Science Scholarship",
    description: "An exclusive initiative that supports young girls who have passed Class 12 Science and want to pursue careers in scientific research or technical fields.",
    category: 'General',
    ministry: "L'Oréal India",
    amount: '₹2,50,000/year',
    amountValue: 250000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 17,
      maxAge: 20,
      maxAnnualIncome: 600000,
      minPercentage: 85,
      educationLevels: ['12th Pass', 'Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['Female'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Science', 'Engineering', 'Medical'],
      professions: ['Student'],
      requiredCriteria: ['Must be female student', 'Completed Class 12 Science with at least 85% score', 'Enrolled in full time BSc, BTech or MBBS'],
      optionalCriteria: [],
      priorityCriteria: [],
    },
    requiredDocuments: ['Income Certificate', 'Marksheet', 'Aadhaar Card'],
    applicationProcess: 'Register on LOréal website. Undergo written exam followed by virtual interview.',
    officialLink: 'https://www.loreal.com/en/india/',
    tags: ['girls', 'science', 'high-value', 'corporate'],
    isActive: true,
  },
  {
    name: 'Sitaram Jindal Foundation Scholarship',
    description: 'An NGO initiative by Jindal Foundation offering monthly stipends to students from 11th grade through postgraduate levels.',
    category: 'General',
    ministry: 'Sitaram Jindal Foundation',
    amount: '₹24,000/year',
    amountValue: 24000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 15,
      maxAge: 30,
      maxAnnualIncome: 250000,
      minPercentage: 60,
      educationLevels: ['10th Pass', '12th Pass', 'Graduation', 'Post Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Science', 'Commerce', 'Arts', 'Engineering', 'Medical', 'Diploma', 'Other'],
      professions: ['Student'],
      requiredCriteria: ['Must be enrolled in recognised school or college', 'Must score minimum 60% for girls and 65% for boys in previous class'],
      optionalCriteria: [],
      priorityCriteria: [],
    },
    requiredDocuments: ['Income Certificate', 'Marksheet', 'Aadhaar Card'],
    applicationProcess: 'Download form, fill out details, attach references, and mail the physical documents to Sitaram Jindal office.',
    officialLink: 'https://www.sitaramjindalfoundation.org',
    tags: ['ngo', 'jindal', 'ug', 'pg'],
    isActive: true,
  },
  {
    name: 'Begum Hazrat Mahal National Scholarship',
    description: 'Central sector scheme for meritorious girls belonging to Minorities (Muslims, Christians, Sikhs, Buddhists, Parsis, Jains).',
    category: 'Minority',
    ministry: 'Ministry of Minority Affairs',
    amount: '₹12,000/year',
    amountValue: 12000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 14,
      maxAge: 20,
      maxAnnualIncome: 200000,
      minPercentage: 50,
      educationLevels: ['10th Pass', '12th Pass'],
      categories: ['All'],
      states: ['All'],
      genders: ['Female'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['All'],
      professions: ['Student'],
      requiredCriteria: ['Must belong to one of the notified minority communities', 'Must be female student', 'Family income must not exceed 2 Lakhs'],
      optionalCriteria: [],
      priorityCriteria: [],
    },
    requiredDocuments: ['Caste/Minority Certificate', 'Income Certificate', 'Marksheet'],
    applicationProcess: 'Apply online on NSP under Ministry of Minority Affairs dropdown.',
    officialLink: 'https://scholarships.gov.in',
    tags: ['minority', 'girls', 'school'],
    isActive: true,
  },
  {
    name: "Prime Minister's Scholarship Scheme for RPF/RPSF",
    description: 'Scholarship sponsored by Ministry of Railways to encourage technical and professional education for wards and widows of ex-RPF/RPSF personnel.',
    category: 'General',
    ministry: 'Ministry of Railways',
    amount: '₹36,000/year',
    amountValue: 36000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 18,
      maxAge: 28,
      maxAnnualIncome: 9999999,
      minPercentage: 60,
      educationLevels: ['12th Pass', 'Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Engineering', 'Medical', 'Diploma', 'Science', 'Commerce', 'Arts'],
      professions: ['Student'],
      requiredCriteria: ['Must be a ward or widow of ex-RPF/RPSF staff', 'Enrolled in an approved professional degree course'],
      optionalCriteria: [],
      priorityCriteria: [],
    },
    requiredDocuments: ['Service Certificate', 'Marksheet', 'Aadhaar Card'],
    applicationProcess: 'Verify relationship and service details, apply via NSP RPF scheme portal.',
    officialLink: 'https://scholarships.gov.in',
    tags: ['railways', 'professional', 'wards', 'defence'],
    isActive: true,
  },
  {
    name: 'Post Matric Scholarship for Students with Disabilities',
    description: 'Financial support for students with 40% or more disability pursuing higher education from Class 11 up to Postgraduate levels.',
    category: 'General',
    ministry: 'Ministry of Social Justice and Empowerment',
    amount: '₹17,000/year',
    amountValue: 17000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 14,
      maxAge: 35,
      maxAnnualIncome: 250000,
      minPercentage: 0,
      educationLevels: ['10th Pass', '12th Pass', 'Graduation', 'Post Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: true,
      bplRequired: false,
      streams: ['All'],
      professions: ['Student'],
      requiredCriteria: ['Must possess a certified disability of 40% or more', 'Family income must not exceed 2.5 Lakhs per annum'],
      optionalCriteria: [],
      priorityCriteria: [],
    },
    requiredDocuments: ['Disability Certificate', 'Income Certificate', 'Marksheet'],
    applicationProcess: 'Apply online on NSP. Requires uploading valid UDID (Unique Disability Identity Card) or state medical board certificate.',
    officialLink: 'https://scholarships.gov.in',
    tags: ['disability', 'pwd', 'post-matric'],
    isActive: true,
  },
  {
    name: 'UP Post Matric Scholarship',
    description: 'State government welfare scheme for Uttar Pradesh domicile students studying in intermediate or degree programs.',
    category: 'General',
    ministry: 'UP Social Welfare Department',
    amount: '₹12,000/year',
    amountValue: 12000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 15,
      maxAge: 30,
      maxAnnualIncome: 200000,
      minPercentage: 0,
      educationLevels: ['10th Pass', '12th Pass', 'Graduation', 'Post Graduation'],
      categories: ['All'],
      states: ['Uttar Pradesh'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['All'],
      professions: ['Student'],
      requiredCriteria: ['Must be permanent resident of Uttar Pradesh', 'Must be studying in UP state registered board or university'],
      optionalCriteria: [],
      priorityCriteria: [],
    },
    requiredDocuments: ['Domicile Certificate', 'Income Certificate', 'Marksheet', 'Aadhaar Card'],
    applicationProcess: 'Apply on UP Scholarship portal (scholarship.up.gov.in). Perform Aadhaar demoseeding authentication.',
    officialLink: 'http://scholarship.up.gov.in',
    tags: ['state', 'uttar-pradesh', 'up-board'],
    isActive: true,
  },
  {
    name: 'Maharashtra Rajarshi Chhatrapati Shahu Maharaj Fee Reimbursement',
    description: 'EBC scholarship scheme for Open/General category students in Maharashtra to subsidise tuition fees for professional higher education.',
    category: 'General',
    cohort: 'EBC',
    ministry: 'Directorate of Higher Education, Maharashtra',
    amount: '₹50,000/year',
    amountValue: 50000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 17,
      maxAge: 28,
      maxAnnualIncome: 800005,
      minPercentage: 50,
      educationLevels: ['12th Pass', 'Graduation'],
      categories: ['All'],
      states: ['Maharashtra'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Engineering', 'Medical', 'Science', 'Commerce', 'Arts', 'Diploma'],
      professions: ['Student'],
      requiredCriteria: ['Domicile of Maharashtra', 'Enrolled in professional or non-professional graduation program under CAP round', 'Family income under 8 Lakhs'],
      optionalCriteria: [],
      priorityCriteria: [],
    },
    requiredDocuments: ['Domicile Certificate', 'Income Certificate', 'Marksheet', 'CAP Admission Letter'],
    applicationProcess: 'Submit online form on Maharashtra MahaDBT portal (mahadbt.maharashtra.gov.in) with college verification.',
    officialLink: 'https://mahadbt.maharashtra.gov.in',
    tags: ['state', 'maharashtra', 'ebc', 'engineering'],
    isActive: true,
  },
  {
    name: 'Karnataka Vidyasiri Scholarship',
    description: 'Backward Classes Welfare Department scheme offering food and accommodation hostel stipends to OBC students pursuing degree courses.',
    category: 'OBC',
    ministry: 'Karnataka Backward Classes Welfare Department',
    amount: '₹15,000/year',
    amountValue: 15000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 17,
      maxAge: 28,
      maxAnnualIncome: 200000,
      minPercentage: 0,
      educationLevels: ['12th Pass', 'Graduation', 'Post Graduation'],
      categories: ['OBC'],
      states: ['Karnataka'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['All'],
      professions: ['Student'],
      requiredCriteria: ['Must be domicile of Karnataka', 'Must belong to Category-1, 2A, 3A, or 3B classes', 'Not staying in government hostels'],
      optionalCriteria: [],
      priorityCriteria: [],
    },
    requiredDocuments: ['Caste Certificate', 'Income Certificate', 'Domicile Certificate', 'Marksheet'],
    applicationProcess: 'Apply online on SSP Karnataka portal (ssp.postmatric.karnataka.gov.in) with valid Kutumba ID.',
    officialLink: 'https://ssp.postmatric.karnataka.gov.in',
    tags: ['state', 'karnataka', 'obc', 'hostel'],
    isActive: true,
  },
  {
    name: 'Vidyasaarathi NSDL Corporate Scholarship',
    description: 'A platform connecting corporate funding with students who need financial support for standard undergraduate or engineering degrees.',
    category: 'General',
    ministry: 'NSDL e-Governance CSR Services',
    amount: '₹40,000/year',
    amountValue: 40000,
    frequency: 'Yearly',
    eligibilityCriteria: {
      minAge: 17,
      maxAge: 26,
      maxAnnualIncome: 500000,
      minPercentage: 60,
      educationLevels: ['12th Pass', 'Graduation'],
      categories: ['All'],
      states: ['All'],
      genders: ['All'],
      disabilityRequired: false,
      bplRequired: false,
      streams: ['Science', 'Engineering', 'Commerce', 'Arts', 'Diploma'],
      professions: ['Student'],
      requiredCriteria: ['Minimum 60% in Class 12 board exam', 'Enrolled in full time graduation degree, engineering degree or diploma'],
      optionalCriteria: [],
      priorityCriteria: [],
    },
    requiredDocuments: ['Income Certificate', 'Marksheet', 'Aadhaar Card'],
    applicationProcess: 'Register on Vidyasaarathi portal, search corresponding corporate scheme, upload verified marksheets and apply.',
    officialLink: 'https://www.vidyasaarathi.co.in',
    tags: ['corporate', 'nsdl', 'ug', 'engineering'],
    isActive: true,
  },
];

const seedDB = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ Connected to MongoDB');

    // Clear existing data
    await Scheme.deleteMany({});
    await EligibilityResult.deleteMany({});
    await Notification.deleteMany({});
    console.log('🗑️  Cleared existing DB data');

    // Generate slug and shortDescription for each scheme since insertMany doesn't run pre-save hooks
    const schemesWithSlugs = schemes.map(s => {
      const slug = s.slug || s.name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
      const shortDescription = s.shortDescription || (s.description.slice(0, 120) + '...');
      return { ...s, slug, shortDescription };
    });

    // Insert schemes
    const created = await Scheme.insertMany(schemesWithSlugs);
    console.log(`✅ Seeded ${created.length} scholarship schemes`);

    // Create a demo admin user
    await User.deleteMany({ email: 'admin@uss.gov.in' });
    const admin = await User.create({
      name: 'USS Admin',
      email: 'admin@uss.gov.in',
      password: 'admin@123',
      role: 'admin',
      isEmailVerified: true,
    });
    console.log(`✅ Admin user created: admin@uss.gov.in / admin@123`);

    // Demo student
    await User.deleteMany({ email: 'student@demo.com' });
    const student = await User.create({
      name: 'Priya Sharma',
      email: 'student@demo.com',
      password: 'demo@123',
      role: 'student',
      isEmailVerified: true,
    });

    await Profile.deleteMany({ user: student._id });
    await Profile.create({
      user: student._id,
      fullName: 'Priya Sharma',
      age: 21,
      gender: 'Female',
      state: 'Maharashtra',
      district: 'Mumbai',
      mobileNumber: '9876543210',
      email: 'student@demo.com',
      educationLevel: '12th Pass',
      stream: 'Science',
      collegeName: 'St. Xavier\'s College',
      cgpaOrPercentage: 88,
      currentYearOrSemester: '1st Year',
      profession: 'Student',
      annualFamilyIncome: 150000, // set below PM National limit
      bplStatus: false,
      category: 'General',
      minorityStatus: false,
      disabilityStatus: false,
      documentUploads: {
        aadhaar: 'https://uss-documents.s3.amazonaws.com/aadhaar_priya.pdf',
        incomeCertificate: '', // initially empty for simulation
        casteCertificate: '',
        domicile: 'https://uss-documents.s3.amazonaws.com/domicile_priya.pdf',
        marksheet: 'https://uss-documents.s3.amazonaws.com/marksheet_priya.pdf',
        disabilityCertificate: ''
      }
    });
    console.log(`✅ Demo student created: student@demo.com / demo@123`);

    // Create initial notification
    await Notification.create({
      user: student._id,
      title: '👋 Welcome to USS Platform',
      message: 'Keep your student profile updated and upload documents to verify scholarship match rates!',
      type: 'info'
    });
    console.log(`✅ Initial welcome notification seeded`);

    console.log('\n🎉 Database seeded successfully!');
    console.log('─────────────────────────────────────');
    console.log('Admin:   admin@uss.gov.in  /  admin@123');
    console.log('Student: student@demo.com  /  demo@123');
    console.log('─────────────────────────────────────');

    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error.message);
    process.exit(1);
  }
};

seedDB();
