const dictionary = {
  en: {
    dashboard: "Dashboard",
    myProfile: "My Profile",
    checkEligibility: "Check Eligibility",
    browseSchemes: "Browse Schemes",
    myResults: "My Results",
    aiHub: "AI Welfare Hub",
    adminDashboard: "Admin Console",
    signOut: "Sign Out",
    profileComplete: "✓ Profile Complete",
    profileIncomplete: "⚠ Complete your profile",
    mainMenu: "Main Menu",
    notifications: "Notifications",
    markAllRead: "Mark all as read",
    noNotifications: "No new notifications",
    welcome: "Welcome back",
    searchSchemes: "Search scholarship schemes...",
    allCategories: "All Categories",
    allStates: "All States",
    allGenders: "All Genders",
    activeSchemes: "Active Schemes",
    matchRate: "Match Rate",
    rejections: "Eligibility Rejections",
    missingDocs: "Missing Documents",
    suggestions: "Suggestions",
    chatQuickSuggest: "Quick Suggest Chips",
    chatPlaceholder: "Ask about your eligibility, document verification...",
    ocrAutofill: "AI Auto-Fill",
    ocrVerify: "Verify Document (OCR)",
    personalDetails: "Personal Details",
    academicDetails: "Academic Details",
    financialDetails: "Financial Details",
    documentsUpload: "Document Uploads",
    nextStep: "Next Step",
    prevStep: "Previous Step",
    saveProfile: "Save Profile & Verify",
    documentVault: "Document Vault",
    noDocuments: "No documents uploaded yet. Upload your academic, income, or category certificates below to complete your profile verification.",
    uploadDocument: "Upload Document",
    selectCategory: "Select Category",
    documentName: "Document Name",
  },
  hi: {
    dashboard: "डैशबोर्ड",
    myProfile: "मेरी प्रोफाइल",
    checkEligibility: "पात्रता जांचें",
    browseSchemes: "योजनाएं खोजें",
    myResults: "मेरे परिणाम",
    aiHub: "एआई कल्याण हब",
    adminDashboard: "एडमिन कंसोल",
    signOut: "साइन आउट",
    profileComplete: "✓ प्रोफाइल पूर्ण",
    profileIncomplete: "⚠ अपनी प्रोफाइल पूरी करें",
    mainMenu: "मुख्य मेनू",
    notifications: "सूचनाएं",
    markAllRead: "सभी को पढ़ा हुआ चिह्नित करें",
    noNotifications: "कोई नई सूचना नहीं",
    welcome: "आपका स्वागत है",
    searchSchemes: "छात्रवृत्ति योजनाएं खोजें...",
    allCategories: "सभी श्रेणियां",
    allStates: "सभी राज्य",
    allGenders: "सभी लिंग",
    activeSchemes: "सक्रिय योजनाएं",
    matchRate: "मिलान दर",
    rejections: "पात्रता अस्वीकृति",
    missingDocs: "लापता दस्तावेज",
    suggestions: "सुझाव",
    chatQuickSuggest: "त्वरित सुझाव चिप्स",
    chatPlaceholder: "अपनी पात्रता, दस्तावेज सत्यापन के बारे में पूछें...",
    ocrAutofill: "एआई ऑटो-फिल",
    ocrVerify: "दस्तावेज सत्यापित करें (OCR)",
    personalDetails: "व्यक्तिगत विवरण",
    academicDetails: "शैक्षणिक विवरण",
    financialDetails: "वित्तीय विवरण",
    documentsUpload: "दस्तावेज़ अपलोड",
    nextStep: "अगला कदम",
    prevStep: "पिछला कदम",
    saveProfile: "प्रोफ़ाइल सहेजें और सत्यापित करें",
    documentVault: "दस्तावेज़ तिजोरी",
    noDocuments: "अभी तक कोई दस्तावेज़ अपलोड नहीं किया गया है। अपनी प्रोफ़ाइल सत्यापन पूरा करने के लिए नीचे अपने शैक्षणिक, आय या श्रेणी प्रमाण पत्र अपलोड करें।",
    uploadDocument: "दस्तावेज़ अपलोड करें",
    selectCategory: "श्रेणी चुनें",
    documentName: "दस्तावेज़ का नाम",
  },
  gu: {
    dashboard: "ડેશબોર્ડ",
    myProfile: "મારી પ્રોફાઇલ",
    checkEligibility: "પાત્રતા તપાસો",
    browseSchemes: "યોજનાઓ શોધો",
    myResults: "મારા પરિણામો",
    aiHub: "એઆઈ કલ્યાણ હબ",
    adminDashboard: "એડમિન કન્સોલ",
    signOut: "સાઇન આઉટ",
    profileComplete: "✓ પ્રોફાઇલ પૂર્ણ",
    profileIncomplete: "⚠ તમારી પ્રોફાઇલ પૂર્ણ કરો",
    mainMenu: "મુખ્ય મેનુ",
    notifications: "સૂચનાઓ",
    markAllRead: "બધાને વાંચેલા તરીકે ચિહ્નિત કરો",
    noNotifications: "કોઈ નવી સૂચના નથી",
    welcome: "આપનું સ્વાગત છે",
    searchSchemes: "સ્કોલરશિપ યોજનાઓ શોધો...",
    allCategories: "બધી શ્રેણીઓ",
    allStates: "બધા રાજ્યો",
    allGenders: "બધા જાતિઓ",
    activeSchemes: "સક્રિય યોજનાઓ",
    matchRate: "મેળ દર",
    rejections: "પાત્રતા અસ્વીકાર",
    missingDocs: "ખૂટતા દસ્તાવેજો",
    suggestions: "સૂચનો",
    chatQuickSuggest: "ઝડપી સૂચન ચિપ્સ",
    chatPlaceholder: "તમારી પાત્રતા, દસ્તાવેજ ચકાસણી વિશે પૂછો...",
    ocrAutofill: "એઆઈ ઓટો-ફિલ",
    ocrVerify: "દસ્તાવેજ ચકાસો (OCR)",
    personalDetails: "વ્યક્તિગત વિગતો",
    academicDetails: "શૈક્ષણિક વિગતો",
    financialDetails: "નાણાકીય વિગતો",
    documentsUpload: "દસ્તાવેજો અપલોડ",
    nextStep: "આગળનું પગલું",
    prevStep: "પાછળનું પગલું",
    saveProfile: "પ્રોફાઇલ સાચવો અને ચકાસો",
    documentVault: "દસ્તાવેજ તિજોરી",
    noDocuments: "હજી સુધી કોઈ દસ્તાવેજો અપલોડ થયા નથી. તમારી પ્રોફાઇલ ચકાસણી પૂર્ણ કરવા માટે નીચે તમારા શૈક્ષણિક, આવક અથવા શ્રેણીના પ્રમાણપત્રો અપલોડ કરો.",
    uploadDocument: "દસ્તાવેજ અપલોડ કરો",
    selectCategory: "શ્રેણી પસંદ કરો",
    documentName: "દસ્તાવેજ નામ",
  }
};

export const t = (key, lang = "en") => {
  const currentLang = dictionary[lang] || dictionary.en;
  return currentLang[key] || dictionary.en[key] || key;
};
